CREATE TABLE LOGIN_INFO (
    USER_ID             VARCHAR(20) NOT NULL PRIMARY KEY COMMENT '사용자아이디',
    USER_PW             VARCHAR(20) DEFAULT NULL COMMENT '비밀번호',
    USER_NAME           VARCHAR(10) DEFAULT NULL COMMENT '이름',
    STATUS              VARCHAR(1) DEFAULT NULL COMMENT '상태',
    USER_DATE           DATETIME DEFAULT NULL COMMENT '마지막접속일자'
);

CREATE TABLE AUTHORITY_INFO (
    USER_ID             VARCHAR(20) NOT NULL COMMENT '사용자아이디',
    AUTHORITY           VARCHAR(10) DEFAULT NULL COMMENT '권한',
    STATUS              VARCHAR(1) DEFAULT NULL COMMENT '상태',
    UPDATE_DATE         DATETIME DEFAULT current_timestamp COMMENT '마지막수정일자',

    FOREIGN KEY (USER_ID) REFERENCES LOGIN_INFO(USER_ID),
    PRIMARY KEY(USER_ID)
);







CREATE TABLE MACHINE_INFO (
    MACHINE_NO          VARCHAR(20) NOT NULL PRIMARY KEY,
    MACHINE_GUBUN       VARCHAR(10) DEFAULT NULL,
    MACHIN_CLASS        VARCHAR(20) DEFAULT NULL,
    MACHINE_USE         VARCHAR(100) DEFAULT NULL,
    MACHINE_NAME        VARCHAR(20) DEFAULT NULL,
    MACHINE_ORDER_NAME  VARCHAR(20) DEFAULT NULL,
    MACHINE_ORDER_DATE  VARCHAR(20) DEFAULT NULL,
    MACHINE_MONEY       VARCHAR(20) DEFAULT NULL,
    MACHINE_PRE         VARCHAR(200) DEFAULT NULL,
    STATUS              VARCHAR(1) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp
);

CREATE TABLE MACHINE_INFO_BODY (
    DATA_ID             BIGINT NOT NULL,
    MACHINE_NO          VARCHAR(20) NOT NULL,
    MACHINE_GUBUN       VARCHAR(20) DEFAULT NULL,
    MACHINE_NAME        VARCHAR(20) DEFAULT NULL,
    MACHINE_REQ_DATE    VARCHAR(20) DEFAULT NULL,
    MACHINE_REQ_MEMO    VARCHAR(100) DEFAULT NULL,
    MACHINE_REP_DATE    VARCHAR(20) DEFAULT NULL,
    MACHINE_REP_MEMO    VARCHAR(100) DEFAULT NULL,
    MONEY               BIGINT DEFAULT NULL,
    MACHINE_REQ_PRE     VARCHAR(20) DEFAULT NULL,
    MACHINE_REP_PRE     VARCHAR(20) DEFAULT NULL,
    STATUS              VARCHAR(200) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp,

    FOREIGN KEY(MACHINE_NO) REFERENCES MACHINE_INFO(MACHINE_NO),
    PRIMARY KEY(DATA_ID, MACHINE_NO)
);







CREATE TABLE ORDER_INFO_HEAD (
    ORDER_NO            VARCHAR(20) NOT NULL PRIMARY KEY,
    ORDER_GUBUN         VARCHAR(5) DEFAULT NULL,
    ORDER_DATE          VARCHAR(10) DEFAULT NULL,
    CUST_NO             VARCHAR(20) DEFAULT NULL,
    MEMO                VARCHAR(200) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp
);

CREATE TABLE ORDER_INFO_BODY (
    DATA_ID             BIGINT NOT NULL,
    ORDER_NO            VARCHAR(20) NOT NULL,
    ITEM_NO             VARCHAR(20) DEFAULT NULL,
    ITEM_NAME           VARCHAR(100) DEFAULT NULL,
    ITEM_CAPACITY       VARCHAR(20) DEFAULT NULL,
    ITEM_QTY            VARCHAR(10) DEFAULT NULL,
    SCHEDUL_DATE        VARCHAR(10) DEFAULT NULL,
    RECIPIENT           VARCHAR(20) DEFAULT NULL,
    RECIPIENT_TEL       VARCHAR(20) DEFAULT NULL,
    RECIPIENT_ZIP       VARCHAR(20) DEFAULT NULL,
    RECIPIENT_ADDRES    VARCHAR(100) DEFAULT NULL,
    MEMO                VARCHAR(200) DEFAULT NULL,
    STATUS              VARCHAR(1) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp,

    FOREIGN KEY(ORDER_NO) REFERENCES ORDER_INFO_HEAD(ORDER_NO),
    PRIMARY KEY(DATA_ID, ORDER_NO)
);







CREATE TABLE MATERIAL_ORDER_HEAD (
    MAT_ORDER_NO        VARCHAR(20) PRIMARY KEY,
    MAT_ORDER_DATE      VARCHAR(10) DEFAULT NULL,
    MAT_ID_DATE         VARCHAR(10) DEFAULT NULL,
    MAT_ORDER_PER       VARCHAR(20) DEFAULT NULL,
    MAT_ORDER_QTY       VARCHAR(10) DEFAULT NULL,
    MAT_ORDER_MONEY     BIGINT DEFAULT NULL,
    MEMO                VARCHAR(200) DEFAULT NULL,
    STATUS              VARCHAR(1) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp
);

CREATE TABLE MATERIAL_ORDER_BODY (
    DATA_ID             BIGINT,
    MAT_ORDER_NO        VARCHAR(20) NOT NULL,
    MAT_ITEM_GUBUN      VARCHAR(1) DEFAULT NULL,
    MAT_ITEM_CODE       VARCHAR(10) DEFAULT NULL,
    MAT_ITEM_NAME       VARCHAR(100) DEFAULT NULL,
    MAT_ITEM_UNIT       VARCHAR(1) DEFAULT NULL,
    MAT_ITEM_QTY        VARCHAR(20) DEFAULT NULL,
    MAT_ITEM_AMT        BIGINT DEFAULT NULL,
    MAT_ITEM_MONEY      BIGINT DEFAULT NULL,
    HS_CODE             VARCHAR(50) DEFAULT NULL,
    MAT_ORDER_PER       VARCHAR(20) DEFAULT NULL,
    MAT_ORDER_TEL       VARCHAR(20) DEFAULT NULL,
    MEMO                VARCHAR(200) DEFAULT NULL,
    STATUS              VARCHAR(1) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp,

    FOREIGN KEY(MAT_ORDER_NO) REFERENCES MATERIAL_ORDER_HEAD(MAT_ORDER_NO),
    PRIMARY KEY(DATA_ID, MAT_ORDER_NO)
);

CREATE TABLE MATERIAL_WEAR (
    MAT_ITEM_CODE       VARCHAR(20) PRIMARY KEY,
    MAT_ITEM_GUBUN      VARCHAR(1) DEFAULT NULL,
    MAT_ITEM_NAME       VARCHAR(100) DEFAULT NULL,
    MAT_ITEM_UNIT       VARCHAR(1) DEFAULT NULL,
    MAT_ITEM_QTY        VARCHAR(1) DEFAULT NULL,
    MAT_ITEM_ATM        BIGINT DEFAULT NULL,
    MAT_ITEM_MONEY      BIGINT DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp,
    DATA_ID             BIGINT NOT NULL, 
    MAT_ORDER_NO        VARCHAR(20) NOT NULL, 

    FOREIGN KEY(DATA_ID) REFERENCES MATERIAL_ORDER_BODY(DATA_ID),
    FOREIGN KEY(MAT_ORDER_NO) REFERENCES MATERIAL_ORDER_BODY(MAT_ORDER_NO)
);

CREATE TABLE MATERIAL_WEAR_HISTORY (
    DATA_ID             BIGINT,
    MAT_ITEM_CODE       VARCHAR(20) NOT NULL,
    MAT_WEAR_DATE       VARCHAR(10) DEFAULT NULL,
    MAT_ITEM_NAME       VARCHAR(100) DEFAULT NULL,
    MAT_ITEM_UNIT       VARCHAR(1) DEFAULT NULL,
    MAT_ITEM_QTY        VARCHAR(20) DEFAULT NULL,
    MAT_ITEM_RQTY       VARCHAR(20) DEFAULT NULL,
    MAT_ITEM_MQTY       VARCHAR(20) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp,

    FOREIGN KEY(MAT_ITEM_CODE) REFERENCES MATERIAL_WEAR(MAT_ITEM_CODE),
    PRIMARY KEY(DATA_ID, MAT_ITEM_CODE)
);

CREATE TABLE MATERIAL_INOUT (
    MAT_INOUT_NO        VARCHAR(20) PRIMARY KEY,
    MAT_INOUT_GUBUN     VARCHAR(1) DEFAULT NULL,
    MAT_INOUT_DATE      VARCHAR(10) DEFAULT NULL,
    MAT_ITEM_GUBUN      VARCHAR(1) DEFAULT NULL,
    MAT_INOUT_GUBUN2    VARCHAR(1) DEFAULT NULL,
    MAT_ITEM_CODE       VARCHAR(10) DEFAULT NULL,
    MAT_ITEM_NAME       VARCHAR(100) DEFAULT NULL,
    MAT_ITEM_UNIT       VARCHAR(1) DEFAULT NULL,
    MAT_ITEM_QTY        VARCHAR(20) DEFAULT NULL,
    MAT_ITEM_ATM        BIGINT DEFAULT NULL,
    MAT_ITEM_MONEY      BIGINT DEFAULT NULL,
    BAR_CODE            VARCHAR(20) DEFAULT NULL,
    HS_CODE             VARCHAR(50) DEFAULT NULL,
    MEMO                VARCHAR(200) DEFAULT NULL,
    STATUS              VARCHAR(1) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp,
    DATA_ID             BIGINT NOT NULL,
    MAT_ORDER_NO        VARCHAR(20) NOT NULL,

    FOREIGN KEY(DATA_ID) REFERENCES MATERIAL_ORDER_BODY(DATA_ID),
    FOREIGN KEY(MAT_ORDER_NO) REFERENCES MATERIAL_ORDER_BODY(MAT_ORDER_NO)
);


CREATE TABLE WORK_ORDER_HEAD (
    WORK_ORDER_NO       VARCHAR(20) PRIMARY KEY,
    WORK_ORDER_GUBUN    VARCHAR(1) DEFAULT NULL,
    WORK_ORDER_DATE     VARCHAR(10) DEFAULT NULL,
    WORK_ORDER_PRE      VARCHAR(20) DEFAULT NULL,
    ITEM_NO             VARCHAR(10) DEFAULT NULL,
    ITEM_NAME           VARCHAR(100) DEFAULT NULL,
    ITEM_CAPACITY       VARCHAR(1) DEFAULT NULL,
    ITEM_QTY            VARCHAR(20) DEFAULT NULL,
    WORK_ORDER_DATE2    VARCHAR(10) DEFAULT NULL,
    MEMO                VARCHAR(200) DEFAULT NULL,
    STATUS              VARCHAR(1) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp
);

CREATE TABLE WORK_ORDER_BODY (
    DATA_ID             BIGINT,
    WORK_ORDER_NO       VARCHAR(10) NOT NULL,
    MAT_ITEM_CODE       VARCHAR(20) NOT NULL,
    MAT_ITEM_NAME       VARCHAR(100) DEFAULT NULL,
    MAT_ITEM_UNIT       VARCHAR(1) DEFAULT NULL,
    MAT_ITEM_QTY        VARCHAR(20) DEFAULT NULL,
    MAT_ITEM_RQTY       VARCHAR(20) DEFAULT NULL,
    STATUS              VARCHAR(1) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp,

    FOREIGN KEY(WORK_ORDER_NO) REFERENCES WORK_ORDER_HEAD(WORK_ORDER_NO),
    PRIMARY KEY(DATA_ID, WORK_ORDER_NO)
);

CREATE TABLE PRODUCT_INOUT (
    DATA_ID             BIGINT,
    PROD_NO             VARCHAR(20) DEFAULT NULL,
    PROD_GUBUN          VARCHAR(1) DEFAULT NULL,
    PRO_NO              VARCHAR(20) DEFAULT NULL,
    PROD_DATE           VARCHAR(10) DEFAULT NULL,
    ITEM_GUBUN          VARCHAR(1) DEFAULT NULL,
    ITEM_CODE           VARCHAR(20) NOT NULL,
    ITEM_NAME           VARCHAR(100) DEFAULT NULL,
    ITEM_CAPACITY       VARCHAR(20) DEFAULT NULL,
    ITEM_UNIT           VARCHAR(1) DEFAULT NULL,
    ITEM_QTY            VARCHAR(20) DEFAULT NULL,
    BAR_CODE            VARCHAR(20) DEFAULT NULL,
    MEMO                VARCHAR(200) DEFAULT NULL,
    STATUS              VARCHAR(1) DEFAULT NULL,
    CREATEUSER          VARCHAR(20) DEFAULT NULL,
    CREATETIME          DATETIME DEFAULT current_timestamp,
    UPDATEUSER          VARCHAR(20) DEFAULT NULL,
    UPDATETIME          DATETIME DEFAULT current_timestamp,
    MAT_INOUT_NO        VARCHAR(20) NOT NULL,
    WORK_ORDER_NO       VARCHAR(20) NOT NULL,

    FOREIGN KEY(DATA_ID) REFERENCES MATERIAL_INOUT(DATA_ID),
    PRIMARY KEY(DATA_ID),
    FOREIGN KEY(MAT_INOUT_NO) REFERENCES MATERIAL_INOUT(MAT_INOUT_NO),
    FOREIGN KEY(WORK_ORDER_NO) REFERENCES WORK_ORDER_HEAD(WORK_ORDER_NO)
);

CREATE TABLE IF NOT EXISTS `warehouse_info` (
  `WAREHOUSE_NO`        varchar(20) NOT NULL,
  `WAREHOUSE_NAME`      varchar(20) DEFAULT NULL,
  `WAREHOUSE_SIZE`      varchar(20) DEFAULT NULL,
  `WAREHOUSE_USE`       varchar(20) DEFAULT NULL,
  `WAREHOUSE_MAX_TEMP`  varchar(10) DEFAULT NULL,
  `WAREHOUSE_MIN_TEMP`  varchar(10) DEFAULT NULL,
  `WAREHOUSE_MAX_HUM`   varchar(10) DEFAULT NULL,
  `WAREHOUSE_MIN_HUM`   varchar(10) DEFAULT NULL,
  `WAREHOUSE_CYCLE`     varchar(10) DEFAULT NULL,
  `STATUS`              varchar(1) DEFAULT NULL,
  `MENO`                varchar(200) DEFAULT NULL,
  `CREATEUSER`          varchar(20) DEFAULT NULL,
  `CREATETIME`          datetime DEFAULT current_timestamp,
  `UPDATEUSER`          varchar(20) DEFAULT NULL,
  `UPDATETIME`          datetime DEFAULT current_timestamp,
  
  PRIMARY KEY (`WAREHOUSE_NO`)
);

CREATE TABLE IF NOT EXISTS `warehouse_info_body` (
  `DATA_ID` bigint(20) NOT NULL,
  `WAREHOUSE_NO` varchar(20) NOT NULL,
  `TEMP` varchar(10) DEFAULT NULL,
  `HUM` varchar(10) DEFAULT NULL,
  `WAREHOUSE_DATE` varchar(10) DEFAULT NULL,
  `WAREHOUSE_TIME` varchar(20) DEFAULT NULL,
  `CREATEUSER` varchar(20) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT current_timestamp,
  `UPDATEUSER` varchar(20) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT current_timestamp,
  FOREIGN KEY(WAREHOUSE_NO) REFERENCES WAREHOUSE_INFO(WAREHOUSE_NO),
  PRIMARY KEY(DATA_ID, WAREHOUSE_NO)
);

CREATE TABLE IF NOT EXISTS `pro_release_head` (
  `PRO_NO` varchar(20) NOT NULL primary key,
  `PRO_DATE` varchar(10) DEFAULT NULL,
  `ITEM_GUBUN` varchar(1) DEFAULT NULL,
  `ITEM_CODE` varchar(20) DEFAULT NULL,
  `ITEM_NAME` varchar(100) DEFAULT NULL,
  `ITEM_CAPACITY` varchar(20) DEFAULT NULL,
  `ITEM_UNIT` varchar(1) DEFAULT NULL,
  `ITEM_QTY` varchar(20) DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  `CREATEUSER` varchar(20) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT current_timestamp,
  `UPDATEUSER` varchar(50) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT current_timestamp,
  `DATA_ID` bigint(20) NOT NULL,
  FOREIGN KEY(DATA_ID) REFERENCES PRODUCT_INOUT(DATA_ID)
);

CREATE TABLE IF NOT EXISTS `pro_release_body` (
  `RELEASE_NO` varchar(20) NOT NULL,
  `RELEASE_DATE` varchar(10) DEFAULT NULL,
  `ITEM_GUBUN` varchar(1) DEFAULT NULL,
  `ITEM_CODE` varchar(20) DEFAULT NULL,
  `ITEM_NAME` varchar(100) DEFAULT NULL,
  `ITEM_CAPACITY` varchar(20) DEFAULT NULL,
  `ITEM_UNIT` varchar(1) DEFAULT NULL,
  `ITEM_QTY` varchar(20) DEFAULT NULL,
  `BAR_CODE` varchar(20) DEFAULT NULL,
  `MEMO` varchar(200) DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  `CREATEUSER` varchar(20) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT current_timestamp,
  `UPDATEUSER` varchar(20) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT current_timestamp,
  `PRO_NO` varchar(20) NOT NULL,
  PRIMARY KEY (`RELEASE_NO`),
  FOREIGN KEY(PRO_NO) REFERENCES pro_release_head(PRO_NO)
);


CREATE TABLE IF NOT EXISTS `product_wear` (
  `ITEM_CODE` varchar(20) NOT NULL DEFAULT '',
  `ITEM_NAME` varchar(100) DEFAULT NULL,
  `ITEM_CAPACITY` varchar(10) DEFAULT NULL,
  `ITEM_QTY` varchar(10) DEFAULT NULL,
  `CREATEUSER` varchar(20) DEFAULT NULL,
  `CREATETIEM` datetime DEFAULT current_timestamp,
  `UPDATEUSER` varchar(20) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT current_timestamp,
  `DATA_ID` bigint(20) NOT NULL DEFAULT 0,
   PRIMARY KEY (`ITEM_CODE`),
   FOREIGN KEY(DATA_ID) REFERENCES PRODUCT_INOUT(DATA_ID)
);

CREATE TABLE IF NOT EXISTS `product_wear_history` (
  `DATA_ID` bigint(20) NOT NULL,
  `PROD_WEAR_DATE` varchar(10) DEFAULT NULL,
  `ITEM_CODE` varchar(20) DEFAULT NULL,
  `ITEM_NAME` varchar(100) DEFAULT NULL,
  `ITEM_CAPACITY` varchar(20) DEFAULT NULL,
  `ITEM_QTY` varchar(20) DEFAULT NULL,
  `ITEM_RQTY` varchar(20) DEFAULT NULL,
  `ITEM_MQTY` varchar(20) DEFAULT NULL,
  `CREATEUSER` varchar(20) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT current_timestamp,
  `UPDATEUSER` varchar(20) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT current_timestamp,
  `ITEM_CODE2` varchar(20) NOT NULL,
  FOREIGN KEY(DATA_ID) REFERENCES PRODUCT_WEAR(DATA_ID),
  FOREIGN KEY(ITEM_CODE2) REFERENCES PRODUCT_WEAR(ITEM_CODE),
  PRIMARY KEY (`DATA_ID`)
);


